# Generated by Django 4.1.6 on 2023-02-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reforest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reforest',
            options={'permissions': (('change_name', 'can change name of product'),)},
        ),
    ]
