# Generated by Django 4.1.6 on 2023-02-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reforest', '0002_alter_category_options_alter_reforest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reforest',
            options={},
        ),
    ]
